ADO WIP

diff --git a/azure-pipeline.yaml b/azure-pipeline.yaml
--- a/azure-pipeline.yaml
+++ b/azure-pipeline.yaml
@@ -28,7 +28,8 @@ resources:
     - container: prime_pipeline_container
       image: dfdsdk/prime-pipeline:0.6.9
       env:
-        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
+        - AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
+        - TF_VAR_s3_bucket: $(BUCKET_NAME)
 
 # Global variables for the pipeline
 variables:
@@ -47,14 +48,15 @@ stages:
         displayName: "Provision infrastructure"
         container: prime_pipeline_container
         steps:
-          # - script: |
-          #     echo 'Checking for required variables...'
-          #     bash -c '[[ -z $AWS_ACCESS_KEY_ID || -z $AWS_SECRET_ACCESS_KEY ]] && exit 1 || true'
-          #   displayName: Init pipeline
+          - script: |
+              echo 'Checking for required variables...'
+              bash -c '[[ -z $AWS_ACCESS_KEY_ID || -z $AWS_SECRET_ACCESS_KEY ]] && exit 1 || true'
+            displayName: Init pipeline
 
-          # - script: |
-          #     terragrunt plan --terragrunt-working-dir ./infrastructure --terragrunt-source-update --terragrunt-non-interactive -input=false
-          #   displayName: Terragrunt Plan
+          - script: |
+              terragrunt plan --terragrunt-working-dir ./infrastructure --terragrunt-source-update --terragrunt-non-interactive -input=false
+              echo Bucket: $TF_VAR_s3_bucket
+            displayName: Terragrunt Plan
 
           # - script: |
           #     terragrunt apply --terragrunt-working-dir ./infrastructure --terragrunt-source-update --terragrunt-non-interactive -input=false -auto-approve
@@ -84,13 +86,13 @@ stages:
                 - download: current
                   artifact: manifests
                   displayName: "Download Artifact: manifests"
+
                 - script: |
                     mkdir -p $(Pipeline.Workspace)/kustomize/
                     kustomize build $(Pipeline.Workspace)/manifests/ > $(Pipeline.Workspace)/kustomize/kustomized.yaml
-                    cat $(Pipeline.Workspace)/kustomize/kustomized.yaml
                   displayName: Kustomize manifests
 
-                # # Apply Kubernetes manifests
+                # Apply Kubernetes manifests
                 # - task: Kubernetes@1
                 #   displayName: "Apply manifests"
                 #   inputs:
